# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 23:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0003_auto_20171226_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttaclmodel',
            name='topic',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^([0-9a-zA-Z\\-_\\/])*\\/$', 'Only Alphanumeric characters, Hyphen, Underscore, Forward-Slash symbols are allowed and must end with Forward-Slash symbol')]),
        ),
        migrations.AlterField(
            model_name='mqttacltemplatemodel',
            name='template',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^([0-9a-zA-Z\\-_\\/]|(%u))*\\/$', 'Only Alphanumeric characters, Hyphen, Underscore, Forward-Slash symbols are allowed plus template arguments like: %u - user-name and must end with Forward-Slash symbol')]),
        ),
    ]
