# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 20:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


def populateMqttAclTemplateModel(apps, schema_editor):
    MqttAclTemplateModel = apps.get_model("auth_manager", "MqttAclTemplateModel")
    template = MqttAclTemplateModel(name='USER_DATA', template='/butler/%u/data/')
    template.save()
    template = MqttAclTemplateModel(name='USER_CONFIG', template='/butler/%u/config/')
    template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0004_auto_20171229_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttacltemplatemodel',
            name='name',
            field=models.CharField(choices=[('USER_DEFAULT', 'USER DEFAULT'), ('USER_DATA', 'USER DATA'), ('USER_CONFIG', 'USER CONFIG')], max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\-_]*$', 'Only Alphanumeric characters, Hyphen and Underscore symbols are allowed')]),
        ),
        migrations.RunPython(
            populateMqttAclTemplateModel
        ),
    ]
