# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 22:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def populateUserLocationModel(apps, schema_editor):
    UserLocationModel = apps.get_model('auth_manager', 'UserLocationModel')
    obj = UserLocationModel(name='UNKNOWN')
    obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0005_auto_20171230_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\-_]*$', 'Only Alphanumeric characters, Hyphen and Underscore symbols are allowed')])),
            ],
            options={
                'verbose_name': 'user location',
                'verbose_name_plural': 'user locations',
                'db_table': 'user_location',
            },
        ),
        migrations.RunPython(
            populateUserLocationModel
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='location',
            field=models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.PROTECT, to='auth_manager.UserLocationModel', to_field='name'),
        ),
    ]
