# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:17
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareAssignmentModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='firmware', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'firmware_assignment',
            },
        ),
        migrations.CreateModel(
            name='FirmwareModel',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\-_]*$', 'Only Alphanumeric characters, Hyphen and Underscore symbols are allowed')])),
                ('hardware', models.CharField(choices=[('ESP8266-4MB', 'ESP8266 with 4MB flash')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=250)),
            ],
            options={
                'db_table': 'firmware',
            },
        ),
        migrations.AddField(
            model_name='firmwareassignmentmodel',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fw_manager.FirmwareModel'),
        ),
    ]
