# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 02:23
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fw_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareAssignmentModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='firmware', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'firmware assignment',
                'verbose_name_plural': 'firmware assignments',
                'db_table': 'firmware_assignment',
            },
        ),
        migrations.CreateModel(
            name='FirmwareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\-_]*$', 'Only Alphanumeric characters, Hyphen and Underscore symbols are allowed')])),
                ('hardware', models.CharField(choices=[('ESP8266-4MB', 'ESP8266 with 4MB flash')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('file', models.FileField(upload_to=fw_manager.models.get_firmware_file_name)),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'firmware',
                'verbose_name_plural': 'firmwares',
                'db_table': 'firmware',
            },
        ),
        migrations.AddField(
            model_name='firmwareassignmentmodel',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fw_manager.FirmwareModel'),
        ),
    ]
