# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fw_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmwareassignmentmodel',
            options={'verbose_name': 'firmware assignment', 'verbose_name_plural': 'firmware assignments'},
        ),
        migrations.AlterModelOptions(
            name='firmwaremodel',
            options={'verbose_name': 'firmware', 'verbose_name_plural': 'firmwares'},
        ),
    ]
