# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateFingerprintModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'cert_fingerprint',
                'ordering': ['created'],
            },
        ),
    ]
