# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatefingerprintmodel',
            options={'ordering': ['created'], 'verbose_name': 'certificate fingerprint', 'verbose_name_plural': 'certificate fingerprints'},
        ),
    ]
